[package]
name = "holo-auto-pilot"
version = "0.1.0"
authors = ["Joel U <joelulahanna@gmail.com>"]
edition = "2018"

[dependencies]
again = "0.1"
anyhow = "1.0"
futures = "0.3"
isahc = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
serde_json = "1.0.60"
structopt = "0.3"
tempfile = "3.1"
tokio = { version = "1", features = ["full"] }
tracing = { version = "0.1", features = ["attributes"] }
tracing-futures = "0.2"
tracing-subscriber = "0.2"
rmp-serde = "0.14.3"
url = "2.2"
observability = "0.1.3"
base64 = "0.13.0"
hc_utils = {git = "https://github.com/holochain/hc-utils", branch = "develop", package = "hc_utils"}
reqwest = { version = "0.11", features = ["json"]}

[dependencies.holochain]
git = "https://github.com/holochain/holochain"
rev = "8d6c4cd29bd17e8224aeffb87dc03eaf3ff33508"
package = "holochain"
default-features = false

[dependencies.holochain_types]
git = "https://github.com/holochain/holochain"
rev = "8d6c4cd29bd17e8224aeffb87dc03eaf3ff33508"
package = "holochain_types"

[dependencies.holochain_websocket]
git = "https://github.com/holochain/holochain"
rev = "8d6c4cd29bd17e8224aeffb87dc03eaf3ff33508"
package = "holochain_websocket"

[dev-dependencies.cargo-husky]
version = "1"
features = ["run-cargo-fmt", "run-cargo-clippy"]

# Holochain requires a patch to crates.io registry
[patch.crates-io]
rkv = { git = "https://github.com/holochain/rkv.git", branch = "master" }
lmdb-rkv = { git = "https://github.com/holochain/lmdb-rs.git" }
holochain_zome_types = {git = "https://github.com/holochain/holochain", rev = "8d6c4cd29bd17e8224aeffb87dc03eaf3ff33508", package = "holochain_zome_types"}
holo_hash = {git = "https://github.com/holochain/holochain", rev = "8d6c4cd29bd17e8224aeffb87dc03eaf3ff33508", package = "holo_hash"}
hdk_derive = {git = "https://github.com/holochain/holochain", rev = "8d6c4cd29bd17e8224aeffb87dc03eaf3ff33508", package = "hdk_derive"}
