[package]
name = "holo-auto-installer"
version = "0.3.0"
authors = ["Joel U <joelulahanna@gmail.com>"]
edition = "2021"

[dependencies]
again = "0.1"
anyhow = "1.0"
arbitrary = "=1.0"
futures = "0.3"
isahc = "0.9"
serde = { version = "=1.0.166", features = ["derive"] }
serde_yaml = "0.8"
serde_json = "1.0.60"
structopt = "0.3"
tempfile = "3.1"
tokio = { version = "1", features = ["full"] }
tracing = { version = "0.1", features = ["attributes"] }
tracing-futures = "0.2"
tracing-subscriber = "0.2"
rmp-serde = "0.15"
url = "2.2"
observability = "0.1.3"
base64 = "0.13.0"
reqwest = { version = "0.11", features = ["json"]}
spinning_top = "0.2.4"
hc_utils = "0.1.0"
holochain_keystore = "0.1.6"
holochain_conductor_api = "0.1.6"
holochain_types = "0.1.6"
holochain_websocket = "0.1.2"
holochain_zome_types = "0.1.4"
mr_bundle = "0.1.2"
holofuel_types = "0.4.0"
getrandom = "0.2.7"
url2 = "0.0.6"
sodoken = "0.0.9"

[dependencies.hpos-config-core]
git = "https://github.com/Holo-Host/hpos-config"
rev = "bfaced6044ae570bf20d4528fa9aaafcc43ddeec"

[dependencies.hpos-config-seed-bundle-explorer]
git = "https://github.com/Holo-Host/hpos-config"
rev = "bfaced6044ae570bf20d4528fa9aaafcc43ddeec"

[dev-dependencies.cargo-husky]
version = "1"
features = ["run-cargo-fmt", "run-cargo-clippy"]
