[package]
name = "holo-auto-installer"
version = "0.1.0"
authors = ["Joel U <joelulahanna@gmail.com>"]
edition = "2021"

[dependencies]
again = "0.1"
anyhow = "1.0"
futures = "0.3"
isahc = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
serde_json = "1.0.60"
structopt = "0.3"
tempfile = "3.1"
tokio = { version = "1", features = ["full"] }
tracing = { version = "0.1", features = ["attributes"] }
tracing-futures = "0.2"
tracing-subscriber = "0.2"
rmp-serde = "1.1.0"
url = "2.2"
observability = "0.1.3"
base64 = "0.13.0"
reqwest = { version = "0.11", features = ["json"]}
spinning_top = "=0.2.0"
hc_utils = "0.0.126"
holofuel_types = "0.1.1"
mr_bundle = "0.0.9"

[dependencies.holochain]
version = "0.0.131"
package = "holochain"
default-features = false

[dependencies.holochain_types]
version = "0.0.31"
package = "holochain_types"

[dependencies.holochain_websocket]
version = "0.0.31"
package = "holochain_websocket"

[dev-dependencies.cargo-husky]
version = "1"
features = ["run-cargo-fmt", "run-cargo-clippy"]
